version: '3.8'
services:
  server:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    image: sing3demons/user-service
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/mydatabase?replicaSet=my-replica-set
      - KAFKA_BROKERS=kafka:9092
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
    networks:
      - ms-service
networks:
  ms-service:
   name: ms-service