version: '3.8'
services:
  mongo1:
    container_name: mongodb-cluster-1
    image: mongo:6.0.3
    command: mongod --replSet mongodb-cluster
    ports:
      - '30001:27017'
    healthcheck:
      test: test $$(echo "rs.initiate({_id:"mongodb-cluster",members:[{_id:0,host:"mongodb-cluster-1:27017"},{_id:1,host:"mongodb-cluster-2:27017"},{_id:2,host:"mongodb-cluster-3:27017"}]})
      interval: 10s
      start_period: 30s
    volumes:
      - ./data/mongodb-cluster-1:/data/db
    networks:
      - ms-service
  mongo2:
    container_name: mongodb-cluster-2
    image: mongo:6.0.3
    command: mongod --replSet mongodb-cluster
    ports:
      - '30002:27017'
    volumes:
      - ./data/mongodb-cluster-2:/data/db
    networks:
      - ms-service
  mongo3:
    container_name: mongodb-cluster-3
    image: mongo:6.0.3
    command: mongod --replSet mongodb-cluster
    ports:
      - '30003:27017'
    volumes:
      - ./data/mongodb-cluster-3:/data/db
    networks:
      - ms-service
networks:
  ms-service:
    name: ms-service

# docker exec -it mongodb-cluster-1 mongosh
# rs.initiate({_id:"mongodb-cluster",members:[{_id:0,host:"mongodb-cluster-1:27017"},{_id:1,host:"mongodb-cluster-2:27017"},{_id:2,host:"mongodb-cluster-3:27017"}]})