name: Docker Image CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/sing3demons/users-service:1.0.0

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ghcr.io/sing3demons/users-service:1.0.0
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
